FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

# Install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends postgresql-client 